# Use postgres/example user/password credentials
version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432